/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/auth/login': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Login and return access token */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['LoginPayload']
                }
            }
            responses: {
                /** @description Login success */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['LoginResponse']
                    }
                }
                400: components['responses']['BadRequest']
                401: components['responses']['Unauthorized']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/logout': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Logout current session */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Logout success */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BooleanResponse']
                    }
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/currentUser': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get current user */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['CurrentUserResponse']
                    }
                }
                401: components['responses']['Unauthorized']
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/user/register': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Register user */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['RegisterPayload']
                }
            }
            responses: {
                /** @description Register success */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['RegisterResponse']
                    }
                }
                400: components['responses']['BadRequest']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/user/list': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** List users */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description User list */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['UserListResponse']
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/page': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** List pages */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Page list */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['PageListResponse']
                    }
                }
            }
        }
        /** Update page */
        put: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['UpdatePagePayload']
                }
            }
            responses: {
                /** @description Page updated */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['PageItemResponse']
                    }
                }
                403: components['responses']['Forbidden']
            }
        }
        /** Create page */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreatePagePayload']
                }
            }
            responses: {
                /** @description Page created */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['PageItemResponse']
                    }
                }
                400: components['responses']['BadRequest']
            }
        }
        /** Soft delete page */
        delete: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': {
                        pageId: string
                    }
                }
            }
            responses: {
                /** @description Soft deleted */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['PageItemResponse']
                    }
                }
            }
        }
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/page/{pageId}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Page detail */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    pageId: components['parameters']['PageIdPath']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Page detail */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['PageItemResponse']
                    }
                }
                404: components['responses']['NotFound']
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/page/{pageId}/acl': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get ACL */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    pageId: components['parameters']['PageIdPath']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description ACL rows */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['DocAclResponse']
                    }
                }
            }
        }
        /** Update ACL */
        put: {
            parameters: {
                query?: never
                header?: never
                path: {
                    pageId: components['parameters']['PageIdPath']
                }
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': {
                        members: components['schemas']['DocAclMember'][]
                    }
                }
            }
            responses: {
                /** @description ACL updated */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['DocAclResponse']
                    }
                }
            }
        }
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/page/{pageId}/comments': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** List comments */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    pageId: components['parameters']['PageIdPath']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Comment threads */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['CommentListResponse']
                    }
                }
            }
        }
        put?: never
        /** Create comment */
        post: {
            parameters: {
                query?: never
                header?: never
                path: {
                    pageId: components['parameters']['PageIdPath']
                }
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreateCommentPayload']
                }
            }
            responses: {
                /** @description Comment created */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['CreateCommentResponse']
                    }
                }
                400: components['responses']['BadRequest']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/comments/{commentId}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        /** Delete comment */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    commentId: components['parameters']['CommentIdPath']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Comment deleted */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['DeleteCommentResponse']
                    }
                }
            }
        }
        options?: never
        head?: never
        /** Update comment */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    commentId: components['parameters']['CommentIdPath']
                }
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['UpdateCommentPayload']
                }
            }
            responses: {
                /** @description Comment updated */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['UpdateCommentResponse']
                    }
                }
            }
        }
        trace?: never
    }
    '/notifications': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** List notifications */
        get: {
            parameters: {
                query?: {
                    status?: components['parameters']['NotificationStatus']
                    cursor?: components['parameters']['CursorQuery']
                    limit?: components['parameters']['LimitQuery']
                }
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Notification list */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['NotificationListResponse']
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/notifications/{id}/read': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        /** Mark one as read */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    id: components['parameters']['NotificationIdPath']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Mark success */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['MarkNotificationReadResponse']
                    }
                }
            }
        }
        trace?: never
    }
    '/notifications/read-all': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        /** Mark all as read */
        patch: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Mark all success */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['MarkAllNotificationsReadResponse']
                    }
                }
            }
        }
        trace?: never
    }
    '/governance/retention': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get retention policy */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Retention policy */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['RetentionPolicyResponse']
                    }
                }
            }
        }
        /** Update retention policy */
        put: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['RetentionPolicy']
                }
            }
            responses: {
                /** @description Retention updated */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['RetentionPolicyResponse']
                    }
                }
            }
        }
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/audit/events': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Query audit events */
        get: {
            parameters: {
                query?: {
                    type?: string
                    actorUserId?: number
                    targetType?: string
                    from?: string
                    to?: string
                    cursor?: components['parameters']['CursorQuery']
                    limit?: components['parameters']['LimitQuery']
                }
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Audit events */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['AuditEventsResponse']
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/audit/stats': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Audit aggregation metrics */
        get: {
            parameters: {
                query?: {
                    days?: number
                }
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Audit stats */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['AuditStatsResponse']
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/audit/emit': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Emit extra audit event */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['EmitAuditPayload']
                }
            }
            responses: {
                /** @description Emit success */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BooleanResponse']
                    }
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/observability/dashboard': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Observability dashboard */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Dashboard metrics */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['ObservabilityDashboardResponse']
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        ErrorResponse: {
            /** @enum {boolean} */
            success: false
            message: string
        }
        BooleanResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                /** @enum {boolean} */
                success: true
            }
        }
        LoginPayload: {
            username: string
            password: string
        }
        RegisterPayload: {
            username: string
            password: string
        }
        User: {
            id: number
            username: string
        }
        LoginResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                access_token: string
            }
        }
        CurrentUserResponse: {
            /** @enum {boolean} */
            success: true
            data: components['schemas']['User']
        }
        RegisterResponse: {
            /** @enum {boolean} */
            success: true
            data: components['schemas']['User']
        }
        UserListItem: {
            id: number
            username: string
            isCurrent: boolean
        }
        UserListResponse: {
            /** @enum {boolean} */
            success: true
            data: components['schemas']['UserListItem'][]
        }
        /** @enum {string} */
        DocRole: 'owner' | 'editor' | 'commenter' | 'viewer'
        /** @enum {string} */
        DocOperation: 'share' | 'member_manage' | 'delete' | 'restore' | 'export' | 'comment_moderate' | 'template_manage' | 'invite_user'
        PageItem: {
            pageId: string
            emoji: string
            title: string
            description?: string | null
            /** Format: date-time */
            createdAt: string
            /** Format: date-time */
            updatedAt: string
            /** Format: date-time */
            deletedAt?: string | null
            /** Format: date-time */
            lastSnapshotAt?: string | null
        }
        CreatePagePayload: {
            emoji: string
            title: string
        }
        UpdatePagePayload: {
            pageId: string
            title: string
        }
        PageListResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                pages: components['schemas']['PageItem'][]
                count: number
            }
        }
        PageItemResponse: {
            /** @enum {boolean} */
            success: true
            data: components['schemas']['PageItem']
        }
        DocAclMember: {
            userId: number
            username: string
            role: components['schemas']['DocRole']
            operations: components['schemas']['DocOperation'][]
        }
        DocAclResponse: {
            /** @enum {boolean} */
            success: true
            data: components['schemas']['DocAclMember'][]
        }
        CommentAnchor: {
            [key: string]: unknown
        }
        CommentThread: {
            commentId: string
            pageId: string
            author?: components['schemas']['User'] | null
            parentCommentId?: string | null
            content: string
            anchor?: components['schemas']['CommentAnchor'] | null
            resolved: boolean
            hidden: boolean
            mentionUserIds: number[]
            /** Format: date-time */
            createdAt: string
            /** Format: date-time */
            updatedAt: string
            /** Format: date-time */
            deletedAt?: string | null
        }
        CreateCommentPayload: {
            content: string
            parentCommentId?: string
            mentionUserIds?: number[]
            mentions?: string[]
            anchor?: components['schemas']['CommentAnchor']
        }
        CreateCommentResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                commentId: string
                content: string
                mentionUserIds: number[]
                invalidMentions: string[]
                /** Format: date-time */
                createdAt: string
            }
        }
        UpdateCommentPayload: {
            content?: string
            resolved?: boolean
            hidden?: boolean
        }
        UpdateCommentResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                commentId: string
                /** Format: date-time */
                updatedAt: string
            }
        }
        DeleteCommentResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                commentId: string
            }
        }
        CommentListResponse: {
            /** @enum {boolean} */
            success: true
            data: components['schemas']['CommentThread'][]
        }
        NotificationItem: {
            notificationId: string
            type: string
            title: string
            content?: string | null
            payload: {
                [key: string]: unknown
            }
            /** Format: date-time */
            readAt: string | null
            /** Format: date-time */
            createdAt: string
        }
        NotificationListResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                unreadCount: number
                nextCursor: string | null
                items: components['schemas']['NotificationItem'][]
            }
        }
        MarkNotificationReadResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                notificationId: string
                success: boolean
            }
        }
        MarkAllNotificationsReadResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                /** @enum {boolean} */
                success: true
                affectedCount: number
            }
        }
        RetentionPolicy: {
            snapshotDays: number
            trashDays: number
            auditDays: number
        }
        RetentionPolicyResponse: {
            /** @enum {boolean} */
            success: true
            data: components['schemas']['RetentionPolicy']
        }
        AuditEventItem: {
            eventId: string
            type: string
            actorUserId: number | null
            targetType: string
            targetId: string | null
            summary: string
            meta: {
                [key: string]: unknown
            }
            /** Format: date-time */
            createdAt: string
        }
        AuditEventsResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                items: components['schemas']['AuditEventItem'][]
                nextCursor: string | null
            }
        }
        AuditStatsResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                days: number
                total: number
                byType: {
                    type: string
                    count: number
                }[]
                trend: {
                    date: string
                    count: number
                }[]
                topActors: {
                    actorUserId: number | null
                    count: number
                }[]
            }
        }
        EmitAuditPayload: {
            type: string
            summary: string
            targetType?: string
            targetId?: string
            meta?: {
                [key: string]: unknown
            }
        }
        ObservabilityDashboardResponse: {
            /** @enum {boolean} */
            success: true
            data: {
                /** @enum {string} */
                mode: 'mock' | 'real'
                /** Format: date-time */
                generatedAt: string
                windows: {
                    aiRateLimitSeconds: number
                    auditTrendDays: number
                }
                definitions: {
                    collaboration: string
                    searchIndex: string
                    aiRateLimit: string
                    audit: string
                }
                collaboration: {
                    wsGateway: string
                    currentConnections: number
                }
                searchIndex: {
                    pendingJobs: number
                    indexedPages: number
                }
                aiRateLimit: {
                    windowSeconds: number
                    maxRequestPerWindow: number
                    hitCount: number
                }
                notifications: {
                    unreadCount: number
                }
                audit: {
                    totalEvents: number
                }
            }
        }
    }
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown
            }
            content: {
                'application/json': components['schemas']['ErrorResponse']
            }
        }
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown
            }
            content: {
                'application/json': components['schemas']['ErrorResponse']
            }
        }
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown
            }
            content: {
                'application/json': components['schemas']['ErrorResponse']
            }
        }
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown
            }
            content: {
                'application/json': components['schemas']['ErrorResponse']
            }
        }
    }
    parameters: {
        PageIdPath: string
        CommentIdPath: string
        NotificationIdPath: string
        CursorQuery: string
        LimitQuery: number
        NotificationStatus: 'all' | 'unread'
    }
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
